# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Lotterypacke' do
    pod 'YTKNetwork', '2.0.1'
    pod 'SDWebImage', '3.8.2'
    pod 'WSProgressHUD', '1.1.1'
    pod 'MJRefresh', '3.1.12'
    pod 'Reachability', '3.2'
    pod 'Masonry', '1.0.2'
    pod 'AJNotificationView', '0.7'
    pod 'TOWebViewController', '2.2.6'
    pod 'SVProgressHUD', '2.1.2'
    pod 'UIAlertView+Blocks', '0.9'
    pod 'IQKeyboardManager'
    pod 'UMengAnalytics', '4.2.4'
    pod 'JPush'
    pod 'JAnalytics'
    pod 'RTLabel', '1.0.1'
    pod 'AFNetworking'
    pod 'MBProgressHUD', '~> 0.9'
    pod 'Bugly'
    pod 'WechatOpenSDK'
    pod 'UIColor+Hex'
    pod 'AMapLocation-NO-IDFA'
    pod 'AMapSearch-NO-IDFA'
    pod 'Toast', '~> 4.0.0'
end
